give @s pa:blender_zero
give @s pa:blender_alpha
give @s pa:circle_sticks
give @s pa:circle_stick
give @s pa:circle_exchange
give @s pa:blender_delta
give @s pa:circle_full
give @s pa:dying_knife_zero
give @s pa:blender_gamma
give @s pa:square_full
give @s pa:machinegun
give @s pa:square_exchange
give @s pa:dying_knife_alpha
give @s pa:mms_corel
give @s pa:mms_corel_m
give @s pa:blender_beta
give @s pa:blender_epsilon
give @s pa:dying_knife_beta
give @s pa:dying_knife_gamma
give @s pa:dying_knife_delta
give @s pa:dying_knife_eplison
give @s pa:coreh
give @s pa:corel
